services:
  santander-api:
    container_name: santander-python-api
    ports:
      - "5000:5000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      # - HOST=host.docker.internal
      - HOST=0.0.0.0
      - PORT=5000
    build: .
    networks:
      - santander

networks:
  santander:
